// Getting the DOM elements
const addItemLink = document.getElementById("add-item-link")
const manageItemLink = document.getElementById("manage-item-link")
const addItemPage = document.getElementById("add-item-page")
const manageItemPage = document.getElementById("manage-item-page")
const itemName = document.getElementById("item-name")
const category = document.getElementById("category")
const color = document.getElementById("color")
const submitItem = document.getElementById("submit-item")
const tableBody = document.getElementById("table-body")